name: Gated Checkin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: gatedAccess
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
