
name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - fixUi
  pull_request:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: gatedAccess
    steps:
      - name: deploy
        uses: actions/checkout@v4
